from Fantasy_Names.hobbit import hobbit
from Fantasy_Names.elf import elf
from Fantasy_Names.french import french
from Fantasy_Names.anglo import anglo
from Fantasy_Names.dwarf import dwarf
from Fantasy_Names.human_diverse import human
from Fantasy_Names.dragonborn import dragonborn
from Fantasy_Names.orc import orc
from Fantasy_Names.gnome import gnome
from Fantasy_Names.tiefling import tiefling