import typing as t

"""
In this file, we store the various string arrays from which names are generated.
"""
warforged_data: t.Dict[str, t.List] = {
    "name1_col1": [
        "walk'",
        "cru$h",
        "lift",
        "sm@sh",
        "guard",
        "scout",
        "vale",
        "1ron",
        "luck",
        "shi3ld",
        "axe",
        "storm",
        "m3rch",
        "sw3lt",
        "bl0ck",
        "vibe",
        "awake",
        "sh3ph",
        "guide",
        "act",
        "stomp",
        "flail",
        "fl@me",
        "dri11",
        "box",
        "beak",
        "prot3ct",
        "insp3ct",
        "dr0n3",
        "f0rge",
        "knit",
    
    ],
    "name1_female_suffixes": ["r", "d", "3d", "er", "d0x", "ker", "k0n", "bot", "dex", "tech"],
    "name1_male_suffixes": [
       "er",
       "0r","@r","ur","1r", "0x", "tr0n", "hu1k", "b0t", "d3x", "t3ch"]
    ,
    "name2_col1": [
        "007",
        "6",
        "00",
        "5",
        "50",
        "1",
        "310",
        "501",
        "000001",
        "612",
        "2",
        "5",
        "3",
        "45",
        "1",
    
    ],

    "name2_col2": [
        "-100",
        "-X",
        "-LTE",
        "-XTRA",
        "-XS",
        "-XL",
        "-S399",
        "-G19",
        "-A4",
        "-A35",
        "-A1",
        "-1290P",
        "",
        "",
    ],

}

tiefling_data: t.Dict[str, t.List] = {
    "name1_col1": [
        "ash'",
        "arch",
        "remi",
        "kil",
        "sol",
        "niro",
        "vale",
        "zhera",
        "gaez",
        "davi",
        "bhad",
        "soph",
        "aeze",
        "aelt",
        "daem",
        "okra",
    ],
    "name1_female_suffixes": ["ivira", "ivera", "sis", "issa", "opheles", "ianna", "iana", "phiones", "oria", "orys", 'belle'],
    "name1_male_suffixes": [
        "teq",
        "thos",
        "par",
        "ossos",
        "muel",
        "herim",
        "riz",
        "lech",
        "dean",
        "rthos",
    ],
    "name2_col1": [
        "revul",
        "pekk",
        "'dalia",
        "carna",
        "fiera",
        "'amarz",
        "voorth",
        "yil",
        "ta",
        "alar",
        "winter",
        "'zether",
        "romz",
        "hyd",
        "szere",
        "'szul",
        "crest",
        "dono",
        "'zether",
        "grim",
    ],

    "name2_col2": [
        "scion",
        "rish",
        "alan",
        "ghan",
        "'crown",
        "'zalan",
        "aeria",
        "reban",
        "helm",
        "haert",
        "'thoum",
        "mast",
        "horn",
        "shadown",
        "abyss",
        "usson",
    ],

}

gnome_data: t.Dict[str, t.List] = {
    "name1_col1": [
        "err'",
        "farn",
        "yelin",
        "bildon",
        "laS",
        "niro",
        "Zil",
        "pari",
        "yoSin",
        "davi",
        "glim",
        "hobbon",
        "fiZZle",
        "lilip",
        "bod",
        "knot",
        "nimble",
    ],
    "name1_female_suffixes": ["vie", "ba", "bieux", "ida", "irra", "nia", "oda", "ana", "*bblebee"],
    "name1_male_suffixes": [
        "teq",
        "wrenn",
        "len",
        "bo",
        "ddo",
        "den",
        "dynn",
        "*bbledob",
        "glim",
        "blen",
    ],
    "name2_col1": [
        "bara",
        "yog",
        "twig",
        "gnorr",
        "perid",
        "gilli",
        "poof",
        "emula",
        "bomble",
        "whit",
        "rumb",
        "fizzle",
        "muwle",
        "wiggle",
        "zul",
        "ferri",
        "yeorro",
        "hwissle",
        "liggle",
        "helio",
        "teeny",


    ],
    "name2_col2": [
        "bell",
        "song",
        "foddle",
        "winner",
        "bumble",
        "nears",
        "aeria",
        "squeem",
        "song",
        "haert",
        "beppo",
        "scheme",
        "inky",
        "laera",
        "icario",
        "mop",
    ],
    "transformations": [
        {"input": "Z", "outputs": ["s", "zs", "zh"]},
        {"input": "S", "outputs": ["ss", "ff", "s"]},
    ],
}

orc_data: t.Dict[str, t.List] = {
    "name1_col1": [
        "kro'",
        "zu",
        "roK",
        "ozghul",
        "gluK",
        "gahx",
        "thush",
        "kulg",
        "draK",
        "Kark",
        "yzz",
        "ogogg",
        "gorb",
        "braK",
        "gornt",
        "snegg",
        "thrash",
    ],
    "name1_female_suffixes": ["ul", "*tha", "lash", "elch", "tharax", "szhah", "holob", "*ungina", "lara"],
    "name1_male_suffixes": [
        "glarz",
        "zug",
        "onkh",
        "arkh",
        "skrash",
        "hoghog",
        "ganth",
        "duk",
        "barg",
        "dush",
    ],
    "name2_col1": [
        "bara",
        "maklo",
        "bazh",
        "guth",
        "shagg",
        "skril",
        "grang",
        "hoong",
        "grik",
        "ogu",
        "zhosh",
        "snoog",
        "targo",
        "yargh",
        "zul",
        "snax",
        "gil",
        "muglug",
        "oosnar",
        "weep",
        "bulz",


    ],
    "name2_col2": [
        "nash",
        "xanth",
        "krash",
        "bak",
        "angok",
        "unthuk",
        "weel",
        "thagub",
        "turzoth",
        "gorgorz",
        "raag",
        "baal",
        "grubdosh",
        "ix",
        "spanx",
        "omosh",
    ],
    "transformations": [
        {"input": "K", "outputs": ["x", "ks", "qu"]},
    ],
}

dragonborn_data: t.Dict[str, t.List] = {
    "name1_col1": [
        "AZA",
        "AnV",
        "cAlA",
        "kAZ",
        "khAAs",
        "dAur",
        "BVm",
        "kaVAr",
        "rhOr",
        "lym",
        "nAxOr",
        "kaZmil",
        "bhArO",
        "VAl",
        "dirr"
    ],
    "name1_female_suffixes": ["ess", "exia", "exius", "lia", "tharax", "hara", "gren", "ina", "daeh", "trix"],
    "name1_male_suffixes": [
        "axus",
        "ghar",
        "raz",
        "gogg",
        "thoth",
        "gauth",
        "goarh",
        "skul",
    ],
    "name2_col1": [
        "light",
        "lord",
        "sever",
        "vlair",
        "hex",
        "idrith",
        "khasar",
        "tore",
        "hkerr",
        "jherit",
        "norix",
        "ghrex",
        "bristle",
        "krash",
        "xerx",
        "miraak",
        "daar",
        "drae",
        "rhae",
        "kimba",
        "prae",
        "brach",
        'tybur',
        'tybin'

    ],
    "name2_col2": [
        "ixius",
        "dandaeon",
        "drough",
        "harglast",
        "angthal",
        "chaebar",
        "valsrath",
        "ymzir",
        "azaad",
        "xtram",
        "azarix",
        "grekan",
        "jordrag",
        "yigma",
        "axaria",
        "jhazir",
        "maxir",
        "rauthux",
        "ezphix",
    ],
    "transformations": [
        {"input": "A", "outputs": ["au", "o", "u"]},
        {"input": "V", "outputs": ["z", "th", "v"]},
        {"input": "Z", "outputs": ["z", "th", "v"]},
    ],
}

hobbit_data: t.Dict[str, t.List] = {
    "name1_col1": [
        "BVB",
        "mVB",
        "frVB",
        "flVB",
        "wVB",
        "lVB",
        "BVm",
        "bilb",
        "BarB",
        "mar",
    ],
    "name1_female_suffixes": ["*a", "*y", "*ia", "lia", "ina", "emina"],
    "name1_male_suffixes": [
        "*o",
        "*y",
        "*ly",
        "*in",
        "win",
        "ius",
        "lius",
        "nus",
    ],
    "name2_col1": [
        "berry",
        "sweet",
        "milk",
        "honey",
        "crumble",
        "jiggle",
        "purple",
        "sneaky",
        "hungry",
        "rumble",
        "prickle",
        "butter",
        "long",
        "short",
        "old",
        "fresh",
        "apple",
        "poppy",
        "fish",
        "cream",
        "wimble",
        "hope",
        "smoke",
        "fiddle",
        "tickle",
        "bubble",
        "brandy",
    ],
    "name2_col2": [
        "muffins",
        "cakes",
        "belly",
        "foot",
        "bum",
        "finger",
        "burrow",
        "toe",
        "tum",
        "weed",
        "scone",
        "biscuits",
        "candles",
        "treats",
        "crust",
        "tart",
        "pipe",
        "feet",
        "wort",
        "sticks",
        "stack",
        "thorp",
        "buck",
    ],
    "transformations": [
        {"input": "B", "outputs": ["t", "d", "b", "p"]},
        {"input": "V", "outputs": ["i", "o", "a", "u"]},
    ],
}

elf_data: t.Dict[str, t.List] = {
    "name1_col1": [
        "RA",
        "gA",
        "gE",
        "ei",
        "ai",
        "ie",
        "gwE",
        "thE",
        "A",
        "E",
        "fA",
        "cA",
    ],
    "name1_col2": ["drAl", "thAn", "vAl", "rAth", "thAr", "rAn", "rAl", "nAl"],
    "name1_female_suffixes": ["a", "ia", "ys", "yn"],
    "name2_col2": [
        "Nther",
        "Nion",
        "Nonus",
        "Niath",
        "Naire",
        "Nuth",
        "Neus",
        "Naine",
        "viel",
    ],
    "transformations": [
        {"input": "A", "outputs": ["a", "a", "e", "e", "ia", "ea", "y"]},
        {"input": "E", "outputs": ["a", "e"]},
        {"input": "N", "outputs": ["n", "m", "l", "r"]},
        {"input": "R", "outputs": ["l", "r"]},
        {"input": "M", "outputs": ["n", "m"]},
    ],
}

dwarf_data: t.Dict[str, t.List] = {
    "name1_col1": [
        "al",
        "an",
        "aur",
        "BAR",
        "Bil",
        "Brun",
        "Bag",
        "Ban",
        "BAn",
        "BArn",
        "eil",
        "faR",
        "ful",
        "gan",
        "gal",
        "grim",
        "gim",
        "hil",
        "lon",
        "skar",
        "vAs",
        "vin",
        "thor",
        "thor",
    ],
    "name1_col2": [
        "viss",
        "arr",
        "angr",
        "vangr",
        "urr",
        "unn",
        "dr",
        "dinn",
        "inn",
        "sten",
    ],
    "name1_col2_female": ["et", "ja", "is", "i", "ssi", "da"],
    "name1_female_suffixes": ["a"],
    "transformations": [
        {"input": "A", "outputs": ["i", "a", "o", "u"]},  # any vowel
        {"input": "R", "outputs": ["l", "r"]},
        {"input": "B", "outputs": ["b", "d", "h"]},
    ],
}

anglo_data: t.Dict[str, t.List] = {
    "name1_col1": [
        "AR",
        "kAR",
        "kAs",
        "rAn",
        "brAn",
        "dAn",
        "frEn",
        "gEn",
        "hAR",
        "sEg",
        "sAN",
        "tIm",
        "bEn",
        "As",
    ],
    "name1_col2": [
        "An",
        "RAm",
        "lAn",
        "nAr",
        "rAth",
        "ric",
        "ret",
        "lyn",
        "mAnd",
        "der",
        "win",
    ],
    "name1_male_suffixes": [
        "ARt",
        "wArd",
        "son",
        "on",
        "fried",
        "wAll",
        "hardt",
        "aRd",
        "ey",
        "duin",
        "ly",
    ],
    "name1_female_suffixes": ["a", "ia", "ie", "isa"],
    "name2_col1": [
        "white",
        "red",
        "black",
        "grey",
        "west",
        "east",
        "fair",
        "rose",
        "grave",
        "wood",
        "daven",
        "ast",
        "avon",
        "bal",
        "bex",
        "blen",
        "brad",
        "row",
        "car",
        "cul",
        "dal",
        "dun",
        "dry",
        "fin",
        "gart",
        "gil",
        "glen",
        "kil",
        "king",
        "kirk",
        "knock",
        "lang",
        "lock",
        "lind",
        "nor",
        "pen",
        "pit",
        "pol",
        "pont",
        "ply",
        "strat",
        "stan",
        "swin",
        "tarn",
        "win",
        "wel",
        "roy",
        "grim",
        "mor",
    ],
    "name2_col2": [
        "beck",
        "berg",
        "berry",
        "bury",
        "burgh",
        "bourne",
        "burn",
        "cott",
        "den",
        "firth",
        "ham",
        "holme",
        "hurst",
        "ing",
        "low",
        "lyn",
        "mere",
        "more",
        "pool",
        "shaw",
        "stead",
        "ster",
        "stow",
        "ton",
        "ward",
        "wick",
        "wich",
        "worth",
        "field",
        "ford",
        "hill",
        "dale",
        "fell",
        "shire",
        "stein",
        "rock",
        "mill",
        "bridge",
        "son",
        "bluff",
    ],
    "transformations": [
        {"input": "E", "outputs": ["a", "i", "e"]},
        {"input": "I", "outputs": ["i", "e", "y"]},
        {"input": "A", "outputs": ["i", "a", "o", "u", "e"]},
        {"input": "R", "outputs": ["l", "r"]},
        {"input": "N", "outputs": ["n", "m"]},
    ],
}

french_data: t.Dict[str, t.List] = {
    "name1_col1": [
        "IN",
        "IB",
        "Il",
        "aB",
        "Is",
        "RuB",
        "RIB",
        "sIB",
        "arn",
        "auB",
        "clIB",
        "BIR",
        "jul",
        "vic",
    ],
    "name1_col2": [
        "ton",
        "is",
        "En",
        "Ant",
        "And",
        "ieR",
        "el",
        "Irt",
        "ois",
        "et",
        "ert",
        "ard",
    ],
    "name1_female_suffixes": [
        "*a",
        "ia",
        "*e",
    ],
    "name1_male_suffixes": [
        "d#ré",
        "eau",
        "aise",
        "r#ien",
        "ein",
        "erré",
        "ain",
    ],
    "name2_col1": [
        "nI",
        "vI",
        "rou",
        "for",
        "bAr",
        "clar",
        "lIv",
        "lI",
        "caste",
        "tour",
        "sAtte",
        "cAlle",
        "I",
        "Atin",
        "hAL",
    ],
    "name2_col2": [
        "ville",
        "val",
        "blAc",
        "mont",
        "court",
        "menil",
        "chatel",
        "vast",
        "bec",
        "dalle",
        "tuit",
        "fleur",
        "lan",
    ],
    "name2_prefixes": ["d'", "de ", "du "],
    "transformations": [
        {"input": "A", "outputs": ["a", "e", "i", "o", "u"]},
        {"input": "I", "outputs": ["e", "a", "i"]},
        {"input": "N", "outputs": ["n", "m"]},
        {"input": "L", "outputs": ["l", "r"]},
        {"input": "B", "outputs": ["l", "r", "m", "n", "c", "ch", "v", "s"]},
    ],
}

compound_tables: t.Dict[str, t.List] = {
    "nature_col1": [
        "green",
        "mist",
        "willow",
        "dream",
        "dusk",
        "night",
        "sage",
        "green",
        "dew",
        "high",
        "bright",
        "cliff",
        "hawk",
        "wind",
        "rain",
        "shadow",
        "sun",
        "cloud",
        "storm",
    ],
    "nature_col2": [
        "wood",
        "shade",
        "glade",
        "blossom",
        "wing",
        "vale",
        "grove",
        "thorn",
        "bark",
        "grass",
        "song",
        "weave",
        "heart",
        "whisper",
        "hunter",
        "root",
    ],
    "mountain_col1": [
        "shield",
        "deep",
        "dark",
        "steel",
        "heavy",
        "grim",
        "stout",
        "battle",
        "iron",
        "stone",
        "dust",
        "mountain",
        "strong",
        "great",
        "proud",
        "brave",
        "gravel",
    ],
    "mountain_col2": [
        "scream",
        "rage",
        "grip",
        "brew",
        "mail",
        "blaze",
        "strike",
        "helm",
        "spear",
        "beard",
        "fury",
        "break",
        "hammer",
        "brow",
        "cask",
        "mace",
        "mead",
        "pike",
        "pick",
    ],
    "generic_col1": [
        "ash",
        "swift",
        "cold",
        "gold",
        "silk",
        "dragon",
        "red",
        "lion",
        "glory",
        "black",
        "blue",
        "hell",
        "demon",
        "fire",
        "wine",
    ],
    "generic_col2": [
        "bane",
        "scar",
        "mark",
        "shine",
        "stride",
        "brand",
        "river",
        "rider",
        "crest",
        "blade",
        "bluff",
        "blood",
        "cloak",
        "born",
        "sworn",
        "fist",
        "ship",
        "arm",
        "gaze",
    ],
}
